[package]
name = "babelfish-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { "workspace" = true }
serde_json = { "workspace" = true }
clap = { "workspace" = true }
ast = { path = "../ast" }
